//-------------------------------------------------
//POV-Ray Materials list
//This file has been created by PoseRay v3.0.2.272
//3D model to POV-Ray/Moray Converter.
//Author: FlyerX
//Email: flyer_2000@excite.com
//Web: http://user.txcyber.com/~sgalls/
//----------------------------------------------------
//Files needed to run the POV-Ray scene:
//POV-Ray configuration file:ROSE_pov.ini Open this file in POV-Ray and press run to obtain the render
//POV-Ray Scene file:ROSE.pov
//POV-Ray geometry mesh file:ROSE_pov.inc
//POV-Ray material file:ROSE_pov_mat.inc
//----------------------------------------------------
//Files used in PoseRay for the creation of this scene:
//3D model file: ROSE.3DS
//Material file: ROSE.mtl
//Camera file: 
//Lights file: 
//----------------------------------------------------
 
 
//Map definitions =================
 
//Material definitions =============================
#declare STEM_dark_blu1= 
texture{pigment {color rgb <0,0.1254902,0.01568628> transmit 0} 
        finish{phong 0.103268 phong_size 140 ambient rgb <0,0.1254902,0.01568628> reflection{0 metallic}}}
//================================================== 
#declare STEM_light_purp= 
texture{pigment {color rgb <0.6,0,0.07450981> transmit 0} 
        finish{phong 0.103268 phong_size 140 ambient rgb <0.6,0,0.07450981> reflection{0 metallic}}}
//================================================== 
#declare STEM_dark_bluis= 
texture{pigment {color rgb <0,0.1254902,0.01568628> transmit 0} 
        finish{phong 0.103268 phong_size 140 ambient rgb <0,0.1254902,0.01568628> reflection{0 metallic}}}
//================================================== 
